### ISSUE TITLE
Enable config_controller execution in Ubuntu

### ISSUE THREAD

**Issue by ericho** [starlingx-staging/stx-packaging#21]
The goal of this issue to get a complete `config_controller` execution in Ubuntu. The findings of this effort will define the basic build and runtime dependencies for configuration of StarlingX system.

## TODO

- [X] Define the build time dependencies of [controllerconfig](https://opendev.org/starlingx/config/src/branch/master/controllerconfig/)
- [X] Create a deb package for tsconfig
- [X] Create a deb package for sysinv
- [X] Create a deb package for controllerconfig
- [ ] Verify that python-oslo-utils is not patched in StarlingX
- [ ] Perform a dry run of `config_controller --config-file <myconf>.ini` in a clean Ubuntu system. 
- [ ] Identify runtime dependencies. If new packages appeared, then create an issue to create the deb for such package.

## Build time dependenciess;

* python-setuptools

## Runtime dependencies

* tsconfig
* sysinv
* python-netaddr
* python-yaml
* python-six
* python-keyring 
* python-netifaces
* python-pyudev
* python-oslo-utils
* fm-api

### Simplex config file

```ini
[SYSTEM]
SYSTEM_MODE = simplex
SYSTEM_TYPE = All-in-one

[OAM_NETWORK]
CIDR = 10.10.10.0/24
GATEWAY = 10.10.10.1
IP_ADDRESS = 10.10.10.3
LOGICAL_INTERFACE = LOGICAL_INTERFACE_1

[LOGICAL_INTERFACE_1]
LAG_INTERFACE = N
INTERFACE_MTU = 1500
INTERFACE_PORTS = enp2s1

[AUTHENTICATION]
ADMIN_PASSWORD = Madawaska1*

[VERSION]
RELEASE = 18.03
```

<details>
<summary>controllerconfig rpm content</summary>
<p>

```
/etc/goenabled.d/config_goenabled_check.sh
/etc/init.d/controller_config
/etc/systemd/system/controllerconfig.service
/etc/upgrade.d
/etc/upgrade.d/16-neutron-move-bindings-off-controller-1.py
/etc/upgrade.d/16-neutron-move-bindings-off-controller-1.pyc
/etc/upgrade.d/16-neutron-move-bindings-off-controller-1.pyo
/etc/upgrade.d/20-sysinv-retire-ceph-cache-tier-sp.py
/etc/upgrade.d/20-sysinv-retire-ceph-cache-tier-sp.pyc
/etc/upgrade.d/20-sysinv-retire-ceph-cache-tier-sp.pyo
/etc/upgrade.d/80-ceilometer-pipeline-migration.sh
/usr/bin/config_controller
/usr/bin/config_management
/usr/bin/config_region
/usr/bin/config_subcloud
/usr/bin/finish_install_clone.sh
/usr/bin/install_clone
/usr/bin/keyringstaging
/usr/bin/openstack_update_admin_password
/usr/bin/tidy_storage_post_restore
/usr/bin/upgrade_controller
/usr/bin/upgrade_controller_simplex
/usr/lib64/python2.7/site-packages/controllerconfig
/usr/lib64/python2.7/site-packages/controllerconfig-1.0.0-py2.7.egg-info
/usr/lib64/python2.7/site-packages/controllerconfig-1.0.0-py2.7.egg-info/PKG-INFO
/usr/lib64/python2.7/site-packages/controllerconfig-1.0.0-py2.7.egg-info/SOURCES.txt
/usr/lib64/python2.7/site-packages/controllerconfig-1.0.0-py2.7.egg-info/dependency_links.txt
/usr/lib64/python2.7/site-packages/controllerconfig-1.0.0-py2.7.egg-info/entry_points.txt
/usr/lib64/python2.7/site-packages/controllerconfig-1.0.0-py2.7.egg-info/top_level.txt
/usr/lib64/python2.7/site-packages/controllerconfig/__init__.py
/usr/lib64/python2.7/site-packages/controllerconfig/__init__.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/__init__.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/backup_restore.py
/usr/lib64/python2.7/site-packages/controllerconfig/backup_restore.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/backup_restore.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/clone.py
/usr/lib64/python2.7/site-packages/controllerconfig/clone.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/clone.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/common
/usr/lib64/python2.7/site-packages/controllerconfig/common/__init__.py
/usr/lib64/python2.7/site-packages/controllerconfig/common/__init__.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/common/__init__.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/common/configobjects.py
/usr/lib64/python2.7/site-packages/controllerconfig/common/configobjects.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/common/configobjects.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/common/constants.py
/usr/lib64/python2.7/site-packages/controllerconfig/common/constants.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/common/constants.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/common/crypt.py
/usr/lib64/python2.7/site-packages/controllerconfig/common/crypt.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/common/crypt.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/common/dcmanager.py
/usr/lib64/python2.7/site-packages/controllerconfig/common/dcmanager.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/common/dcmanager.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/common/exceptions.py
/usr/lib64/python2.7/site-packages/controllerconfig/common/exceptions.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/common/exceptions.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/common/keystone.py
/usr/lib64/python2.7/site-packages/controllerconfig/common/keystone.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/common/keystone.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/common/log.py
/usr/lib64/python2.7/site-packages/controllerconfig/common/log.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/common/log.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/common/rest_api_utils.py
/usr/lib64/python2.7/site-packages/controllerconfig/common/rest_api_utils.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/common/rest_api_utils.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/common/validator.py
/usr/lib64/python2.7/site-packages/controllerconfig/common/validator.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/common/validator.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/config_management.py
/usr/lib64/python2.7/site-packages/controllerconfig/config_management.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/config_management.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/configassistant.py
/usr/lib64/python2.7/site-packages/controllerconfig/configassistant.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/configassistant.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/openstack.py
/usr/lib64/python2.7/site-packages/controllerconfig/openstack.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/openstack.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/progress.py
/usr/lib64/python2.7/site-packages/controllerconfig/progress.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/progress.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/regionconfig.py
/usr/lib64/python2.7/site-packages/controllerconfig/regionconfig.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/regionconfig.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/sysinv_api.py
/usr/lib64/python2.7/site-packages/controllerconfig/sysinv_api.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/sysinv_api.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/systemconfig.py
/usr/lib64/python2.7/site-packages/controllerconfig/systemconfig.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/systemconfig.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/tests
/usr/lib64/python2.7/site-packages/controllerconfig/tests/__init__.py
/usr/lib64/python2.7/site-packages/controllerconfig/tests/__init__.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/tests/__init__.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/tests/test_answerfile.py
/usr/lib64/python2.7/site-packages/controllerconfig/tests/test_answerfile.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/tests/test_answerfile.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/tests/test_region_config.py
/usr/lib64/python2.7/site-packages/controllerconfig/tests/test_region_config.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/tests/test_region_config.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/tests/test_system_config.py
/usr/lib64/python2.7/site-packages/controllerconfig/tests/test_system_config.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/tests/test_system_config.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/tidy_storage.py
/usr/lib64/python2.7/site-packages/controllerconfig/tidy_storage.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/tidy_storage.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/__init__.py
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/__init__.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/__init__.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/controller.py
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/controller.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/controller.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/management.py
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/management.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/management.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/utils.py
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/utils.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/upgrades/utils.pyo
/usr/lib64/python2.7/site-packages/controllerconfig/utils.py
/usr/lib64/python2.7/site-packages/controllerconfig/utils.pyc
/usr/lib64/python2.7/site-packages/controllerconfig/utils.pyo
/usr/share/doc/controllerconfig-1.0
/usr/share/doc/controllerconfig-1.0/LICENSE
```

</p>
</details>

**Comment by ericho** [comment]
After satisfy all dependencies, `config_controller` fails with the following error: 

```
WARNING: Command should only be run from the console. Continuing with this
terminal may cause loss of connectivity and configuration failure.


Configuration failed: Two or more network devices are required
```

**Comment by marcelarosalesj** [comment]
Hi erich, these three bullets are complete now:
* Create a deb package for tsconfig
* Create a deb package for sysinv
* Create a deb package for controllerconfig  
Where or how can I get a simple `<myconf>.ini` file to test the config_controller command?

**Comment by ericho** [comment]
Thanks for the update @marcelarosalesj !
