### ISSUE TITLE
Enable an installer for an All In One system in Ubuntu

### ISSUE THREAD

**Issue by ericho** [starlingx-staging/stx-packaging#22]
To enable an installer in Ubuntu the next exploratory tasks needs to be done. We'll assume that we will build only a AIO system. 

## TODO

- [ ] Verify what is the purpose of [anaconda patches](https://opendev.org/starlingx/integ/src/branch/master/base/anaconda/centos). 
- [ ] Verify what is the purpose of the [rpm patches](https://opendev.org/starlingx/integ/src/branch/master/base/rpm).
- [ ] Check which verifications the kickstart files does before installing. For example, it checks for  number of cpus and hard drives. 
- [ ] Get the list of packages installed in a AIO installation. This can be reviewed after running `build-iso` in `$MY_WORKSPACE/export`.
- [ ] Check the post installation steps make by kickstarts. For example, the creation of content in `/opt`
- [ ] Review the process of autogeneration of kickstart and grub configuration files.
- [ ] Decide an installation method for Ubuntu. Seems there are different ways to install Ubuntu. Also verify which one matches best the usage of anaconda.
